<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (

  'edit' => '編輯',
  'create' => '建立',
  'delete' => '刪除',
  'view' => '檢視',
  'news' => '最新消息',
  'home' => '首頁',
  'you are here' => '現在位置',
  'admin list' => '管理員設定',
  'username' => '帳號',
  'name' => '名稱',
  'admin details' => '管理員資料',
  'records per page' => '筆資料一頁',
  'go to page..' => '前往頁面',
  'go' => '前往',
  'search' => '篩選',
  'of' => '自',
  'showing page' => '顯示頁面',
  'items' => '項目',
  'save' => '儲存',
  'password' => '密碼',
  'user list' => '會員名單管理',
  'email' => '信箱',
  'user details' => '會員名單資料',
  'address' => '地址',
  'phone' => '電話',
  'slider list' => '首頁slider',
  'slider details' => '首頁slider資料',
  'upload photo' => '上傳照片',
  'photo' => '照片',
  'sequence' => '順序',
  'active' => '上架設定',
  'url' => '網址',
  'report list' => '單元內容管理',
  'report details' => '單元內容資料',
  'content' => '內容',
  'date' => '日期',
  'channel' => '頻道',
  'file upload' => '檔案上傳',
  'news list' => '最新消息',
  'news details' => '最新消息資料',
  'video list' => '影音專區',
  'video details' => '影音專區資料',
  'category' => '分類',
  'set main photo' => '設為主圖片',
  'rent list' => '租買諮詢',
  'rent details' => '租買諮詢資料',
  'logout' => '登出',
  'permission' => '權限',
  'read' => '檢視',
  'update' => '更新',
  'module' => '模組',
  'select all' => '全選',
  'administrator' => '管理員',
  'member' => '使用者',
  'dashboard' => '佈告欄',
  'next →' => '下一頁',
  'first page' => '第一頁',
  'last page' => '最後頁',
  '← previous' => '上一頁',
  'company' => '公司行號',
  'phone 2' => '電話2',
  'zzzzzzzzzzzzzzzzzzzzzzzz' => 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'type requirement' => '類型需求',
  'ground requirement' => '坪數需求',
  'yes' => '是',
  'no' => '否',
  'status mark' => '狀態註記',
  'export' => '匯出',
  'save success' => '儲存成功',
  'save failed' => '儲存失敗',
  'size' => '坪數',
  'phone 1' => '電話1',
  'memo' => '備註',
  'status' => '狀態',
  'rent record' => '租貸紀錄',
  'phone home' => '聯絡電話-室內',
  'phone mobile' => '聯絡電話-手機',
  'is in' => '是否進駐',
  'youtube url' => 'Youtube網址',
  'tags' => '標籤',
  'from' => '出處',
  'author' => '作者',
  'Role' => '使用者身份',
  'zzzzzzzzzzzzzzzzzzzzzzzz' => 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzz' => 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
   


  );
